#include "packagewriter.h"
#include "colorschemebuilder.h"
#include "metadatawriter.h"

#include <QDir>
#include <QFileInfo>
#include <QFile>
#include <QProcess>
#include <QDebug>

/*
 * PackageWriter
 * -----------------------------
 * Handles creation of distributable Plasma 6 theme packages.
 * Steps:
 *   1. Verify output directory & theme name
 *   2. Generate .colors file via ColorSchemeBuilder
 *   3. Generate metadata.json via MetadataWriter
 *   4. (Phase 3+) Optionally zip into a .kpackage archive
 *   5. Emit signals on success/failure for UI handling
 */

PackageWriter::PackageWriter(QObject *parent)
: QObject(parent)
{
}

/*
 * writePackage()
 * -----------------------------
 * Combines all export steps into a single operation.
 * Returns true if all files were successfully created.
 */
bool PackageWriter::writePackage(const QString &outputDir,
                                 const QString &themeName)
{
    if (outputDir.isEmpty() || themeName.isEmpty()) {
        Q_EMIT errorOccurred(QStringLiteral("Output directory or theme name is empty."));
        return false;
    }

    QDir outDir(outputDir);
    if (!outDir.exists()) {
        Q_EMIT errorOccurred(QStringLiteral("Output directory does not exist."));
        return false;
    }

    // --- Step 1: Save the color scheme --------------------------
    const QString colorsFilePath = outDir.filePath(themeName + QStringLiteral(".colors"));
    ColorSchemeBuilder builder;
    const bool colorsOk = builder.saveToFile(colorsFilePath);
    if (!colorsOk) {
        Q_EMIT errorOccurred(QStringLiteral("Failed to save .colors file."));
        return false;
    }

    // --- Step 2: Generate metadata.json -------------------------
    MetadataWriter metadata;
    const QString metadataPath = outDir.filePath(QStringLiteral("metadata.json"));
    const bool metaOk = metadata.writeMetadata(
        outputDir, themeName,
        QStringLiteral("1.0"),
                                               QStringLiteral("GPL-3.0-or-later"),
                                               QStringLiteral("Generated by Kreate")
    );
    if (!metaOk) {
        Q_EMIT errorOccurred(QStringLiteral("Failed to write metadata.json."));
        return false;
    }

    // --- Step 3: (Optional) Package into .zip / .kpackage --------
    // Placeholder: KF6::Package API or QProcess call to `kpackagetool6`
    // will be implemented in the final export phase.
    // Example (commented out for now):
    /*
     *   const QString zipPath = outDir.filePath(themeName + QStringLiteral(".kcolorpackage"));
     *   QProcess zipProc;
     *   zipProc.start(QStringLiteral("zip"), { QStringLiteral("-r"), zipPath, themeName });
     *   zipProc.waitForFinished();
     *   if (zipProc.exitStatus() != QProcess::NormalExit) {
     *       Q_EMIT errorOccurred(QStringLiteral("Failed to create package archive."));
     *       return false;
}
*/

    // --- Step 4: Notify success ---------------------------------
    Q_EMIT packageWritten(colorsFilePath);
    qDebug() << "PackageWriter: Successfully exported theme at" << outputDir;
    return true;
}
